apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-security.fullname" . }}-db
  labels:
    {{- include "java-security.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
