apiVersion: v1
kind: Secret
metadata:
  name: java-security-db-credentials
  namespace: java-security
type: Opaque
stringData:
  db-url: "jdbc:postgresql://postgres-service:5432/java_security"
  db-username: "java_user"
  db-password: "changeme123"
