apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-security
  namespace: java-security
  labels:
    app: java-security

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: java-security-role
  namespace: java-security
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-security-rolebinding
  namespace: java-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: java-security-role
subjects:
- kind: ServiceAccount
  name: java-security
  namespace: java-security
